In [1]:

import torch
import torchvision
import warnings
import torch.nn as nn
import torch.nn.functional as F
from torch import optim
import torchvision.transforms as transforms
from torch.utils.data.dataset import random_split
import matplotlib.pyplot as plt
from numpy.random import randint


warnings.filterwarnings('ignore')



In [2]:

batch_size = 128
lr = 0.003
num_epoch = 20


In [3]:

dataset = torchvision.datasets.MNIST(root='./data',
                                     train=True,
                                     download=True,
                                     transform=transforms.Compose([
                                         transforms.ToTensor()
                                     ]))

In [4]:

lengths = [int(len(dataset)*0.8), int(len(dataset)*0.2)]
train_set, val_set = random_split(dataset, lengths)


In [5]:


batch_size= 100
train_loader = torch.utils.data.DataLoader(train_set,
                                           batch_size=batch_size,
                                           shuffle=True,
                                           drop_last=True,
                                           pin_memory=True)

val_loader = torch.utils.data.DataLoader(val_set,
                                         batch_size=batch_size,
                                         shuffle=True,
                                         drop_last=True,
                                         pin_memory=True)

print(dataset.targets.bincount())
print(dataset.targets.unique())


tensor([5923, 6742, 5958, 6131, 5842, 5421, 5918, 6265, 5851, 5949])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [6]:

batch_size = 1
lr = 0.003
num_epoch = 20


In [7]:

dataset = torchvision.datasets.MNIST(root='./data',
                                     train=True,
                                     download=True,
                                     transform=transforms.Compose([
                                         transforms.ToTensor()
                                     ]))

In [8]:

lengths = [int(len(dataset)*0.8), int(len(dataset)*0.2)]
train_set, val_set = random_split(dataset, lengths)


In [9]:


batch_size= 100
train_loader = torch.utils.data.DataLoader(train_set,
                                           batch_size=batch_size,
                                           shuffle=True,
                                           drop_last=True,
                                           pin_memory=True)

val_loader = torch.utils.data.DataLoader(val_set,
                                         batch_size=batch_size,
                                         shuffle=True,
                                         drop_last=True,
                                         pin_memory=True)

print(dataset.targets.bincount())
print(dataset.targets.unique())


tensor([5923, 6742, 5958, 6131, 5842, 5421, 5918, 6265, 5851, 5949])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [10]:


batch_size= 1
train_loader = torch.utils.data.DataLoader(train_set,
                                           batch_size=batch_size,
                                           shuffle=True,
                                           drop_last=True,
                                           pin_memory=True)

val_loader = torch.utils.data.DataLoader(val_set,
                                         batch_size=batch_size,
                                         shuffle=True,
                                         drop_last=True,
                                         pin_memory=True)

print(dataset.targets.bincount())
print(dataset.targets.unique())


tensor([5923, 6742, 5958, 6131, 5842, 5421, 5918, 6265, 5851, 5949])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [11]:


batch_size= 128
train_loader = torch.utils.data.DataLoader(train_set,
                                           batch_size=batch_size,
                                           shuffle=True,
                                           drop_last=True,
                                           pin_memory=True)

val_loader = torch.utils.data.DataLoader(val_set,
                                         batch_size=batch_size,
                                         shuffle=True,
                                         drop_last=True,
                                         pin_memory=True)

print(dataset.targets.bincount())
print(dataset.targets.unique())


tensor([5923, 6742, 5958, 6131, 5842, 5421, 5918, 6265, 5851, 5949])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
